#!/run/current-system/sw/bin/bash

CONFIG_PATH="/var/tmp/scr_light/current_red_value"

monitor_count=$(hyprctl monitors all | grep Monitor | wc -l)

if [[ $(echo $MONITOR_TYPE ) == "internal" ]]; then
  cmd_more="brillo -A 10"
  cmd_less="brillo -U 10"
  cmd_max="brillo -S 100"
  cmd_min="brillo -S 0"
elif [[ $(echo $MONITOR_TYPE) == "external" ]]; then
  cmd_max=""
  cmd_min=""
  cmd_more=""
  cmd_less=""
  for i in $(seq 1 $monitor_count); do
    cmd_more+="ddcutil --display $i setvcp 10 + 10"
    cmd_less+="ddcutil --display $i setvcp 10 - 10"
    cmd_max+="ddcutil --display $i setvcp 10 100"
    cmd_min+="ddcutil --display $i setvcp 10 0"
    if [[ $i != $monitor_count ]]; then
      cmd_max+=" && "
      cmd_min+=" && "
      cmd_more+=" && "
      cmd_less+=" && "
    fi
  done
fi

echo $cmd_more
echo $cmd_less

light_down() {

  case "$1" in
  "max")
    eval $cmd_min
    exit 0
    ;;
  *)
    eval $cmd_less
    exit 0
    ;;
  esac
}

light_up() {

  case $1 in
  "max")
    eval $cmd_max
    exit 0
    ;;
  *)
    eval $cmd_more
    exit 0
    ;;
  esac
}

case "$1" in

"up")
  light_up
  ;;

"down")
  light_down
  ;;

"blue")
  hyprshade off
  ;;

"red")
  hyprshade on blue-light-filter
  ;;

"day")
  light_up max
  ;;
"night")
  light_down max
  ;;
*) echo "unknown command" && exit 1 ;;

esac
